use_frameworks!
use_modular_headers!
platform :ios, '12.0'

target 'AccessibilitySnapshotDemo' do
	# Paralayout does not support Xcode 12 in the current release version. Support will be added in 1.0 (see
	# square/Paralayout#23), so once that's released we can switch back to the release version.
	pod 'Paralayout', :git => 'https://github.com/square/Paralayout'

	target 'SnapshotTests' do
		inherit! :search_paths

		pod 'AccessibilitySnapshot/iOSSnapshotTestCase', :path => '../AccessibilitySnapshot.podspec'
		pod 'AccessibilitySnapshot/SnapshotTesting', :path => '../AccessibilitySnapshot.podspec'

		# SnapshotTesting dropped support for building with Xcode 10 in 1.8.0, so pin the version to 1.7 in order to
	    # run our tests against Xcode 10.
	    pod 'SnapshotTesting', '= 1.7.2'
	end

	target 'UnitTests' do
		inherit! :search_paths

		pod 'AccessibilitySnapshot/Core', :path => '../AccessibilitySnapshot.podspec'
	end
end

project 'AccessibilitySnapshot.xcodeproj'

install! 'cocoapods', :disable_input_output_paths => true
