use_frameworks!
use_modular_headers!
platform :ios, '13.0'

target 'AccessibilitySnapshotDemo' do
	pod 'Paralayout', '= 1.0.0-rc.5'

	target 'SnapshotTests' do
		inherit! :search_paths

		pod 'AccessibilitySnapshot/iOSSnapshotTestCase', :path => '../AccessibilitySnapshot.podspec'
	end

	target 'UnitTests' do
		inherit! :search_paths

		pod 'AccessibilitySnapshot/Core', :path => '../AccessibilitySnapshot.podspec'
	end
end

project 'AccessibilitySnapshot.xcodeproj'

install! 'cocoapods', :disable_input_output_paths => true
