import ProjectDescription

let workspace = Workspace(
    name: "AccessibilitySnapshot",
    projects: ["."],
    generationOptions: .options(
        autogeneratedWorkspaceSchemes: .disabled
    )
)
