language: objective-c
jobs:
  - osx_image: xcode11.6
    env: ACTIONS="xcode";PLATFORM="iOS_12"
install:
  - bundle install --gemfile=Example/Gemfile
  - bundle exec --gemfile=Example/Gemfile pod install --project-directory=Example
script:
  - ./Scripts/ci.sh
branches:
  only:
  - master
